repos:
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      args: ["--line-length", "119"]
      language_version: python3.9
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: ["-r", "application/eth2"]
      language_version: python3.9